version: '3.7'
services:
    lara_app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_api
        user: "${UID}"
        volumes:
            - ./:/var/www
            - ./data/composer:/.composer
            - ./logs/laravel:/var/www/var/logs:cached
        depends_on:
            - mysql
            - redis
    nginx:
        image: nginx:latest
        ports:
            - "8187:80"
            - "4433:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - lara_app
    redis:
        image: redis:latest
        ports:
          - "6380:6379"
    mysql:
        image: mysql:5.7.21
        command: --init-file /data/app/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_api_db
            MYSQL_USER: docker
            MYSQL_PASSWORD: laraapi
        ports:
            - "8787:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/init.sql:/data/app/init.sql
    mail:
        image: djfarrelly/maildev
        ports:
            - 25
            - 8127:80