version: '3.7'
services:
    lara_app_api:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_api
        user: "${UID}"
        networks:
          - docker-shared-services
        volumes:
            - ./:/var/www
            - ./data/composer:/.composer
            - ./logs/laravel:/var/www/var/logs:cached
        depends_on:
            - mysql_api
            - redis_api
            - rabbitmq_api
    nginx_api:
        image: nginx:latest
        ports:
            - "8187:80"
            - "4433:443"
        networks:
          - docker-shared-services
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - lara_app_api
    redis_api:
        image: redis:latest
        networks:
          - docker-shared-services
        ports:
          - "6380:6379"
    mysql_api:
        image: mysql:5.7.21
        command: --init-file /data/app/init.sql
        container_name: laraapi_db
        networks:
          - docker-shared-services
        environment:
            MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "8787:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/init.sql:/data/app/init.sql
    mail_api:
        image: djfarrelly/maildev
        ports:
            - 25
            - 8127:80

    rabbitmq_api:
        image: rabbitmq:3-management
        networks:
            - docker-shared-services
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"

networks:
  docker-shared-services:
    external: true
