version: 2.1
jobs:
    build:
      docker:
          - image: docker:stable
      steps:
        - checkout
        - run: docker info
    deploy:
      machine:
        enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - "0c:33:a8:8c:40:06:fa:ae:13:c8:63:a6:e7:52:a1:b0"
        - run:
            name: Deploy Over SSH to VPS server 
            command: |
              ssh -t $SSH_USER_VPS@$SSH_HOST_VPS "cd $PROJECT_DIR && touch test.txt && ls -la"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: feature/Setting_up_CI_CD
