version: 2.1
jobs:

    build:
      docker:
          - image: docker:stable
      steps:
        - checkout
        - run: docker info
    test:
      docker:
        - image: circleci/php:7.3-stretch-node-browsers
        - image: circleci/mysql:5.7.26
          environment:
            MYSQL_DATABASE: laravel_api_db_test
            MYSQL_USER: docker
            MYSQL_PASSWORD: laraapi
        - image: selenium/standalone-chrome:3
      steps:
        - checkout
        - run: sudo docker-php-ext-install -j$(nproc) pdo_mysql zip mysqli
        - run: sudo composer self-update
        - run: sudo composer install -n --prefer-dist --ignore-platform-reqs
        - save_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
            paths:
              - vendor
        - run: cp behat.dist.remote behat.yml
        - run: cp .env.behat.deploy .env
#        - run:
#            name: Install MySQL CLI
#            command: |
#              sudo apt-get install mysql-client
#              mysql -h 127.0.0.1 -u docker -plaraapi
        - run: php artisan key:generate
        - run: php artisan migrate
        - run: php artisan passport:install
        - run: php -S 127.0.0.1:8080 -t ./public &> /dev/null &
        - run: php -S 127.0.0.1:8080 -t ./public &> /dev/null && vendor/bin/behat --tags @api

    deploy:
      machine:
        enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - "0c:33:a8:8c:40:06:fa:ae:13:c8:63:a6:e7:52:a1:b0"
        - run:
            name: Deploy Over SSH to VPS server 
            command: |
              ssh -t $SSH_USER_VPS@$SSH_HOST_VPS "cd $PROJECT_DIR && touch test.txt && ls -la"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
              branches:
                only: develop
      - test:
          filters:
            branches:
              only: feature/Setting_up_CI_CD
      - deploy:
          filters:
            branches:
              only: develop
